#!/bin/sh

create_dir() { #cree directory dir_name si n'existe pas
if test -f $* -o -d $*
then
   if test ! -d $*
   then
     echo "ERREUR ==> $* n'est pas un directory"
     exit
   fi
return 0
else
   echo "creation de $*"
   mkdir $*
fi
}

create_dir i386_linux_lib
create_dir i386_linux_exe
make -f makefile.unix "VERSION = i386_linux" "COMPILAT=gcc"  "COMPFOR=g77" "LINK=gcc" "CFLAGS=-DUSERFORTRAN" "LD_FOR=-lg2c" "FFLAGS=-fno-second-underscore" "MAKEEXTENSION=for"
