#!/bin/sh

create_dir() { #cree directory dir_name si n'existe pas
if test -f $* -o -d $*
then
   if test ! -d $*
   then
     echo "ERREUR ==> $* n'est pas un directory"
     exit
   fi
return 0
else
   echo "creation de $*"
   mkdir $*
fi
}

create_dir sun_lib
create_dir sun_exe
make -f makefile.unix "VERSION = sun" "COMPILAT=gcc" "COMPFOR=f77" "LINK=f77" "CFLAGS=-DUSERFORTRAN" "MAKEEXTENSION=for" 
