#!/bin/sh

create_dir() { #cree directory dir_name si n'existe pas
if test -f $* -o -d $*
then
   if test ! -d $*
   then
     echo "ERREUR ==> $* n'est pas un directory"
     exit
   fi
return 0
else
   echo "creation de $*"
   mkdir $*
fi
}

create_dir i386-linux_lib
create_dir i386-linux_exe

make -f makefile.unix "VERSION = i386-linux" "COMPILAT=g++" "LINK=gcc"


