ifeq ($(WITH_RANGE_YANEZ),yes)
	EXTRA_CXX_FLAGS += -I$(RANGE_YANEZ_DIR)/include -DWITH_RANGE_YANEZ
	EXTRA_LIBRARIES += -L$(RANGE_YANEZ_DIR)/lib -lrange
else ifeq ($(WITH_MODIFIED_RANGE_YANEZ),yes)
	EXTRA_CXX_FLAGS += -I$(RANGE_YANEZ_DIR)/include -DWITH_RANGE_YANEZ -DWITH_MODIFIED_RANGE_YANEZ
	EXTRA_LIBRARIES += -L$(RANGE_YANEZ_DIR)/lib -lrange
else
	NOT_READY += stopping/KVRangeYanez.cpp stopping/KVRangeYanezMaterial.cpp
endif

include Makefile.KVMultiDet

