ifeq ($(ROOTGANILTAPE),yes)
	EXTRA_CXX_FLAGS += -DROOTGANILTAPE -I$(GANTAPE_INC) -D__unix -D__linux -fbounds-check
else
	NOT_READY += analysis/KVIVRawDataReconstructor.cpp analysis/KVIVRawDataAnalyser.cpp
endif

ETC_DATA = $(shell ls factory/*Template.[c,h]*)
MANIP_DIRS = VAMOS_e503
			
include Makefile.VAMOS
