#ifdef __CINT__
#include "RVersion.h"
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;
#pragma link C++ class KVVarGlob;
#pragma link C++ class KVVarGlob1;
#pragma link C++ class KVVarGlobMean;
#pragma link C++ class KVVGSum;
#pragma link C++ class KVGVList;
#pragma link C++ class KVZtot;
#pragma link C++ class KVZmean;
#pragma link C++ class KVZbound;
#pragma link C++ class KVZBoundMean;
#pragma link C++ class KVZtotAv;
#pragma link C++ class KVZboundAv;
#pragma link C++ class KVZmax;
#pragma link C++ class KVEtrans;
#pragma link C++ class KVEtransLCP;
#pragma link C++ class KVEkin;
#pragma link C++ class KVCaloBase;
#pragma link C++ class KVCalorimetry;
#pragma link C++ class KVPtot;
#pragma link C++ class KVZVtot;
#pragma link C++ class KVSource;
#pragma link C++ class KVMultIMF;
#pragma link C++ class KVMultLeg;
#pragma link C++ class KVMultAv;
#pragma link C++ class KVMultIMFAv;
#pragma link C++ class KVMultLegAv;
#pragma link C++ class KVTenseur3;
#pragma link C++ class KVTensP;
#pragma link C++ class KVTensE;
#pragma link C++ class KVTensPCM;
#pragma link C++ class KVRiso;
#pragma link C++ class KVFoxH2;
#pragma link C++ class KVRisoAv;
#pragma link C++ class KVRelativeVelocity;
#pragma link C++ class KVQuadMoment;
#pragma link C++ class KVFlowTensor;
#pragma link C++ class KVRotatedTensor;
#endif
