# Linux / G++

CXX           = g++
LD            = g++

#needed on my machine (installation bugged ?)
EXTRA_LDFLAGS = -lstdc++
EXTRA_CXXFLAGS= -fPIC
DPDFLAGS_ARCH = -I/usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include
SOFLAGS       = -Wl -shared
