#!/bin/csh -f
setenv DIR_PERSO `pwd`
setenv HPSS_DIR "cchpssindra:/hpss/in2p3.fr/group/indra"
echo " "
echo "         ------------------------------------------"
echo "        |                                          |"
echo "        |       LECTURE des runs DST INDRA         |"
echo "        |        sur zone HPSS (LINUX)             |"
echo "        |                                          |"
echo "        | D. Cussol                   8 Mars 2003  |"
echo "        | J-L. Charvet             9 fevrier 2004  |"
echo "        | O. Lopez                    4 Juin 2004  |"
echo "         ------------------------------------------"
echo " "
echo "Menu :"
echo " "
echo "     1............ runs DST 1ere campagne"
echo "     2............ runs DST 2eme campagne"
#echo "     3............ runs DST 3eme campagne"
echo "     4............ runs DST 4eme campagne version 2 (Mai 2004)"
echo " "
echo -n "Votre choix : "
set rep=$<
setenv CAMPAGNE $rep
if ( $rep == "1" ) then
	setenv VEDA_FOR '/afs/in2p3.fr/home/throng/indra/veda1/for'
	setenv VEDA_LIBS "$THRONG_DIR/lib/kali_linux.o -L$THRONG_DIR/lib -lkali_linux"
	setenv VEDA_DATA '/afs/in2p3.fr/home/throng/indra/veda1/files/'
	setenv VEDAROOT_FOR "$KVROOT/src/faire_arbre.f"
	setenv nomkdc $THRONG_DIR/any/hpss/vedahpss.camp_93
	setenv DATA_SET "INDRA_camp1"
endif
if ( $rep == "2" ) then
	setenv VEDA_FOR '/afs/in2p3.fr/home/throng/indra/veda2/for'
	setenv VEDA_LIBS "$THRONG_DIR/lib/kali_2_linux.o"
	setenv VEDA_DATA '/afs/in2p3.fr/home/throng/indra/veda2/data/'
	setenv VEDAROOT_FOR "$KVROOT/src/faire_arbre_c2.f"
	setenv nomkdc $THRONG_DIR/any/hpss/vedahpss.camp_2
	setenv DATA_SET "INDRA_camp2"
endif
#if ( $rep == "3" ) then
#   $THRONG_DIR/any/hpss/vedahpss_c3_lec
#endif
if ( $rep == "4" ) then
	setenv VEDA_FOR '/afs/in2p3.fr/home/throng/indra/veda4/for/include'
	setenv VEDA_DATA     '/afs/in2p3.fr/home/throng/indra/veda4/data/'
	setenv VEDAROOT_FOR "$KVROOT/src/faire_arbre_c4.f"
	setenv VEDA_LIBS "$THRONG_DIR/lib/veda4/vishnou_sub_linux.o"
	setenv nomkdc $THRONG_DIR/any/hpss/vishnouhpss.camp_4_v2
	setenv DATA_SET "INDRA_camp4"
endif
veda2root_kali96
exit

