#ifdef __CINT__
#include "RVersion.h"
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;
#pragma link C++ namespace KVUnits;
#pragma link C++ global gHistoManipulator;
#pragma link C++ enum KVBase::EKaliVedaBits;
#pragma link C++ function SearchFile(const Char_t*, TString&, int);
#pragma extra_include "Rtypes.h";
#pragma link C++ class Binary_t<UChar_t>+;
#pragma link C++ class Binary_t<UShort_t>+;
#pragma link C++ class Binary_t<UInt_t>+;
#pragma link C++ class Binary_t<Long64_t>+;
#pragma link C++ class KVString+;
#pragma link C++ class KVRungeKutta+;
#pragma link C++ class Hexa_t+;
#pragma link C++ class KVNameValueList+;
#pragma link C++ class KVBase-;//customised streamer
#pragma link C++ class KVColouredBase+;
#pragma link C++ class KVClassFactory+;
#pragma link C++ class KVClassMethod+;
#pragma link C++ class KVClassMember+;
#pragma link C++ class KVClassMonitor+;
#pragma link C++ class KVSeqCollection-;
#pragma link C++ class KVDataBranchHandler+;
#pragma link C++ class KVDatime+;
#pragma link C++ class KVDatedFileManager+;
#pragma link C++ class KVHashList+;
#pragma link C++ class KVUniqueNameList+;
#pragma link C++ class KVList-;
#pragma link C++ class KVLockfile+;
#pragma link C++ class KVNamedParameter+;
#pragma link C++ class KVLogReader+;
#pragma link C++ class KVBQSLogReader+;
#pragma link C++ class KVGELogReader+;
#pragma link C++ class KVMemoryChunk+;
#pragma link C++ class KVMemoryPool+;
#pragma link C++ class KVNumberList+;
#pragma link C++ class KVFileReader;
#pragma link C++ class KVValues;
#pragma link C++ class KVRList+;
#pragma link C++ class KVSortableDatedFile+;
#pragma link C++ class KVTarArchive+;
#pragma link C++ class KVHistoManipulator;
#pragma link C++ class KVEventListMaker;
#pragma link C++ class KVUpdateChecker;
#pragma link C++ class KVCVSUpdateChecker;
#pragma link C++ class KVSystemFile+;
#pragma link C++ class KVSystemDirectory+;
#pragma link C++ class KVEnv+;
#pragma link C++ class KVHistogram+;
#pragma link C++ class KVPosition+;
#pragma link C++ class KVIntegerList-;
#pragma link C++ class KVCouple+;
#pragma link C++ class KVPartitionGenerator+;
#pragma link C++ class KVPartition+;
#pragma link C++ class KVPartitionFromLeaf+;
#pragma link C++ class KVPartitionList+;
#pragma link C++ class KVPartitionFunction+;
#pragma link C++ class TF1Derivative;
#endif
