#!/bin/csh -f
#Prints out ROOT version and associated environment variables
echo "Using ROOT version `root-config --version`"
echo "ROOTSYS=$ROOTSYS"
echo "PATH = $PATH"
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
exit
