#!/bin/csh -f

echo "----------------------------------------"
echo "   lancement de KALI en INTERACTIF  "
echo "----------------------------------------"

#---- Ajout des eventuelles librairies supplementaires ----------
set prgm_sup=$REP_LIBS/libkali_camp"$CAMPAGNE"_sup.a
if ( -e $prgm_sup ) then
	echo existe
	setenv VEDA_LIBS ""$REP_LIBS"/kali_lecture_dst_camp"$CAMPAGNE".o -L"$REP_LIBS" -lkali_camp"$CAMPAGNE"_sup"
else
	setenv VEDA_LIBS "$REP_LIBS"/kali_lecture_dst_camp"$CAMPAGNE".o
endif

#------ Compilation ------------------
echo ' start of compilation and load ' `date`
g77 -v -I$VEDA_FOR $FOR_PERSO $VEDA_LIBS -ox$RUN_PREFIX `cernlib pawlib mathlib` 
if ($status != '0') then
   echo ' Big problem with the compilation '
   exit 99
endif
echo '  end of compilation and load ' `date`

#--------
#set nomfic="$NOMFI.cart"
#set WRITE="0"
#if( $CAMPAGNE == "4" ) then
#	echo "$WRITE   Lecture de cartouches DST" >> $nomfic
#else
#	echo "$WRITE Pas d'ecriture de cartouches reduites" >> $nomfic
#endif
#
#echo $DST_FILE >> $nomfic

#echo "Fichier nomfic=$nomfic :"
#cat $nomfic
#echo " "

#if ( $CAMPAGNE == "4" ) then
#	echo "EOF EOF 0" >> $nomfic
#else
#	echo "EOF 0 EOF 0" >> $nomfic
#endif

#------ Running ....---------------------------
echo ' Execution begins ...' `date`
./x$RUN_PREFIX
echo ' Execution ends .....' `date`  

#rm x$NOMFI
#rm $nomfic
#------> D.Cussol : Instructions de fin de tache (copies de fichiers par exemple)
#ls -l
#rm r[0-9]*
#---------------------------------------------
# Transformation of text file to ROOT/KaliVeda file
#source $KVROOT/bin/fin_$PFOR.exe
exit

