#!/bin/csh -f
#
if ( $?QSUB_REQNAME ) then
    echo "----------------------------------------"
    echo "     veda2root_lanceur in BATCH mode "
    echo "----------------------------------------"
endif
#
cd $DIR_PERSO
set prefix="run"
setenv NEVENTS 0
setenv HPSS_RUNS "$INPUT"
foreach i ($HPSS_RUNS)
   set jobname="$prefix$i"
   setenv INPUT $i
   setenv NOMFI $jobname
   qsub -eo -l CPUBound,platform=LINUX,T=$TIME,M=$MEMORY,scratch=$DISK,hpss -N $jobname -V $KVROOT/bin/veda2root_kali
end 
exit
