#!/bin/bash -f
# Prints out KaliVeda version and associated environment variables

progname=`basename $0`
showpaths=no
showkvroot=no

function usage () {
   cat <<EOF
Usage: $progname [-p] [-r] [-h]
   Display name of currently-used version of KaliVeda
   -p   display PATH and LD_LIBRARY_PATH variables
   -r   display KVROOT variable
   -h   display this help message
EOF
   exit 0
}

while getopts ":prh" opt; do
   case $opt in

   p )  showpaths=yes ;;
   r )  showkvroot=yes ;;
   h )  usage ;;
   \?)  usage ;;
   esac
done

shift $(($OPTIND - 1))

vers_file=$HOME/.kalivedaversion
if [ -e $vers_file ] ; then
	version=`cat $vers_file | awk '{ print $1 }'`
   if [ $version == "standard" ] ; then
      echo "Using standard KaliVeda version"
   elif [ $version != "" ] ; then
      echo "Using KaliVeda version \"$version\""
   fi
else
   echo "Version information for KaliVeda is unknown"
   exit 0
fi
if [ x"$showkvroot" == "xyes" ] ; then
	echo "KVROOT = $KVROOT"
fi
if [ x"$showpaths" == "xyes" ] ; then
	echo "PATH = $PATH"
	echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
fi
exit 0
