#!/bin/bash -f
# Prints out ROOT and associated environment variables

progname=`basename $0`
showpaths=no
showrootsys=no

function usage () {
   cat <<EOF
Usage: $progname [-p] [-r] [-h]
   Display currently-used version of ROOT
   -p   display PATH and LD_LIBRARY_PATH variables
   -r   display ROOTSYS variable
   -h   display this help message
EOF
   exit 0
}

while getopts ":prh" opt; do
   case $opt in

   p )  showpaths=yes ;;
   r )  showrootsys=yes ;;
   h )  usage ;;
   \?)  usage ;;
   esac
done

shift $(($OPTIND - 1))

echo "Using ROOT version `root-config --version`"
if [ "x$showrootsys" == "xyes" ] ; then
	echo "ROOTSYS=$ROOTSYS"
fi
if [ "x$showpaths" == "xyes" ] ; then
	echo "PATH = $PATH"
	echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
fi
exit 0
