#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class KVINDRAIDTelescope+;
#pragma link C++ class KVIDSiCsI+;
#pragma link C++ class KVIDSiCsI_e475s+;
#pragma link C++ class KVIDSiLiCsI+;
#pragma link C++ class KVIDSi75SiLi+;
#pragma link C++ class KVIDChIoSi+;
#pragma link C++ class KVIDChIoSi75+;
#pragma link C++ class KVIDChIoSi_e475s+;
#pragma link C++ class KVIDChIoCsI_e475s+;
#pragma link C++ class KVIDCsI_e475s+;
#pragma link C++ class KVIDCsI+;
#pragma link C++ class KVIDPhoswich+;
#pragma link C++ class KVIDChIoCsI+;
#pragma link C++ class KVIDSi150CsI_camp5+;
#pragma link C++ class KVIDChIoSi5+;
#pragma link C++ class KVIDChIoSiCorr+;
#pragma link C++ class KVIDChIoSi75_camp5+;
#pragma link C++ class KVIDChIoCsI_camp5+;
#pragma link C++ class KVIDChIoCorrCsI+;
#pragma link C++ class KVIDSiCsI5+;
#pragma link C++ class KVIDSiCorrCsI+;
#pragma link C++ class KVIDSi75SiLi_camp5+;
#pragma link C++ class KVIDSiLiCsI_camp5+;
#pragma link C++ class KVIDBlocking+;
#endif
